# Generated by Django 3.2.16 on 2022-12-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('catergory', models.CharField(choices=[('SBD', 'SINGLE_BED'), ('DBD', 'DOUBLE_BED'), ('VIP', 'DELUXE_ROOM'), ('NIP', 'NORMAL_ROOM')], max_length=3)),
                ('beds', models.IntegerField()),
                ('capacity', models.IntegerField()),
            ],
        ),
    ]
