# Generated by Django 3.2.16 on 2022-12-13 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_auto_20221213_2234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='check_in',
            new_name='checking_in',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='check_out',
            new_name='checking_out',
        ),
    ]
