# Generated by Django 3.2.16 on 2022-12-14 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0003_auto_20221213_2252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='number',
            new_name='roomnumber',
        ),
    ]
