# Generated by Django 3.2.16 on 2022-12-14 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0004_rename_number_room_roomnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='catergory',
            new_name='category',
        ),
    ]
