# Generated by Django 3.2.16 on 2022-12-14 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0005_rename_catergory_room_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='category',
            new_name='Category',
        ),
    ]
