# Generated by Django 3.2.16 on 2022-12-14 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0006_rename_category_room_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='Category',
            new_name='category',
        ),
    ]
